const faceEmojis = {
  grinning: '😀',
  grin: '😁',
  joy: '😂',
  rolling_on_the_floor_laughing: '🤣',
  nerd_face: '🤓',
  face_with_monocle : '🧐',
  zany_face: '🤪',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  stuck_out_tongue_closed_eyes: '😝',
  smiley: '😃',
  smile: '😄',
  sweat_smile: '😅',
  laughing: '😆',
  innocent: '😇',
  smiling_imp: '😈',
  wink: '😉',
  blush: '😊',
  yum: '😋',
  relieved: '😌',
  heart_eyes: '😍',
  sunglasses: '😎',
  smirk: '😏',
  neutral_face: '😐',
  expressionless: '😑',
  unamused: '😒',
  sweat: '😓',
  pensive: '😔',
  confused: '😕',
  confounded: '😖',
  kissing: '😗',
  kissing_heart: '😘',
  kissing_smiling_eyes: '😙',
  kissing_closed_eyes: '😚',

  disappointed: '😞',
  worried: '😟',
  angry: '😠',

  cry: '😢',
  persevere: '😣',
  triumph: '😤',
  disappointed_relieved: '😥',
  frowning: '😦',
  anguished: '😧',
  fearful: '😨',
  weary: '😩',
  sleepy: '😪',
  tired_face: '😫',
  grimacing: '😬',
  sob: '😭',
  open_mouth: '😮',
  hushed: '😯',
  cold_sweat: '😰',
  scream: '😱',
  astonished: '😲',
  flushed: '😳',
  sleeping: '😴',
  dizzy_face: '😵',
  no_mouth: '😶',
  mask: '😷',
  slightly_frowning_face: '🙁',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  face_with_rolling_eyes: '🙄',
  sneezing_face: '🤧',
  face_with_raised_eyebrow: '🤨',
  star_struck: '🤩',
  smiling_face_with_3_hearts: '🥰',
  yawning_face: '🥱',
  partying_face: '🥳',
  woozy_face: '🥴',

  cold_face: '🥶',
  shushing_face: '🤫',
  hot_face: '🥵',
  rage: '😡',
  face_with_symbols_on_mouth: '🤬',
  face_with_hand_over_mouth: '🤭',
  face_vomiting: '🤮',
  exploding_head: '🤯',
  zipper_mouth_face: '🤐',
  money_mouth_face: '🤑',
  face_with_thermometer: '🤒',
  thinking_face: '🤔',
  face_with_head_bandage: '🤕',
  face_with_cowboy_hat: '🤠',
  clown_face: '🤡',
  nauseated_face: '🤢',
  drooling_face: '🤤',
  lying_face: '🤥',

  red_envelope: '🧧',
  wilted_flower: '🥀',
  heartbeat: '💓',
  heart: '❤️',
  broken_heart: '💔',
  two_hearts: '💕',
  sparkling_heart: '💖',
  heartpulse: '💗',
  cupid: '💘',
  blue_heart: '💙',
  green_heart: '💚',
  yellow_heart: '💛',
  purple_heart: '💜',
  gift_heart: '💝',

}

export default faceEmojis;