const PeopleEmojis = {
    woman: '👩',
    male_student: '👨‍🎓',
    male_singer: '👨‍🎤',
    male_artist: '👨‍🎨',
    male_teacher: '👨‍🏫',
    male_factory_worker: '👨‍🏭',
    man_boy_boy: '👨‍👦‍👦',
    white_haired_woman: '👩‍🦳',
    female_doctor: '👩‍⚕️',
    female_judge: '👩‍⚖️',
    female_pilot: '👩‍✈️',
    bride_with_veil: '👰',
    blond_haired_woman: '👱‍♀️',
    person_with_blond_hair: '👱‍♂️',
    man_with_gua_pi_mao: '👲',
    man_with_turban: '👳‍♂️',
    older_man: '👴',
    older_woman: '👵',
    baby: '👶',
    construction_worker: '👷‍♂️',
    princess: '👸',
    bearded_person: '🧔',
    person_with_headscarf: '🧕',
    person_in_steamy_room: '🧖‍♂️',
    couple: '👫',
    two_men_holding_hands: '👬',
    women_holding_hands: '👭',
    couplekiss: '💏',
    female_police_officer: '👮‍♀️',
    cop: '👮‍♂️',
    elf: '🧝‍♂️',
    female_genie: '🧞‍♀️',
    genie: '🧞‍♂️',
    man_in_lotus_position: '🧘‍♂️',
    mage: '🧙‍♀️',
    male_mage: '🧙‍♂️',
    fairy: '🧚‍♀️',
    vampire: '🧛‍♀️',
    mrs_claus: '🤶',
    shrug: '🤷',
    merman: '🧜‍♂️',
    woman_in_motorized_wheelchair: '👩‍🦼',
    woman_in_manual_wheelchair: '👩‍🦽',

    zombie: '🧟‍♂️',
    person_climbing: '🧗‍♀️',
    standing_person: '🧍',
    kneeling_person: '🧎',
    deaf_woman: '🧏‍♀️',
    deaf_man: '🧏‍♂️',

    person_doing_cartwheel: '🤸',
    juggling: '🤹',
    fencer: '🤺',
    wrestlers: '🤼',
    water_polo: '🤽',
    handball: '🤾',

    snowboarder: '🏂',
    running: '🏃‍♂️',
    woman_surfing: '🏄‍♀️',
}
export default PeopleEmojis